language: go
go:
  - 1.7.5
matrix:
  allow_failures:
  - go: tip
script:
  - for pkg in $(go list | grep -v /vendor/);do go vet $pkg; done
  - for pkg in $(go list | grep -v /vendor/);do go test $pkg; done
